# Workflow to deploy with IG Publisher and Shorthand to the hl7austria.github.io repository

name: PublishIGWithHL7International

# Run on updates to the master
on:
  push:
    branches: [ ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout the implementation guide
      uses: actions/checkout@v2
      with:
        repository: HL7Austria/HL7-AT-FHIR-Core-R5
        path: .

    - name: Checkout FHIR IG Web Templates
      uses: actions/checkout@v2
      with:
        repository: HL7/fhir-web-templates
        path: ./fhir-web-templates

    - name: Checkout FHIR IG History Templates
      uses: actions/checkout@v2
      with:
        repository: HL7/fhir-ig-history-template
        path: ./fhir-ig-history-templates

    - name: Checkout FHIR IG Registry
      uses: actions/checkout@v2
      with:
        repository: HL7Austria/ig-registry
        path: ./fhir-ig-registry

    - name: Extract branch name
      run: |
        if ["${{ github.event.pull_request.head.ref }}" == ""]; then
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        else
          echo "##[set-output name=branch;]$(echo ${{ github.event.pull_request.head.ref }})"
        fi
      id: extract_branch
    
    - name: Extract last commit date
      shell: bash
      run: echo "##[set-output name=date;]$(git log -1 --format="%at" | xargs -I{} date -d @{} +%d.%m.%Y)"   
      id: extract_date
      
    - uses: bluwy/substitute-string-action@v1
      id: substitute_index
      with:
        _input-file: input/landing_page/_index.yml
        _format-key: '%%key%%'
        branch: ${{ steps.extract_branch.outputs.branch }}
        date: ${{ steps.extract_date.outputs.date }}
        _output-file: input/landing_page/_index.yml

    - name: Install NPM
      uses: actions/setup-node@v2.1.2
      with:
        check-lastest: true
        
    - name: Install Sushi
      run: sudo npm install -g fsh-sushi

    - name: Install Jekyll
      run: |
        sudo apt-get install jekyll
        
    - name: Download IG Publisher
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: 'latest'
        path: .
        file: publisher.jar
        
    - name: Run IG Publisher
      run: | 
        mkdir input-cache
        mv publisher.jar ./input-cache/publisher.jar
        unset DISPLAY
        java -Djava.awt.headless=true -jar ./input-cache/publisher.jar -ig ig.ini

    - name: Move index file and files for gopublish
      run: |         
        mv ./input/landing_page/_index.yml ./output/
        mkdir ./output_published
        cp ./publication-feed.xml ./output_published/publication-feed.xml
        cp ./package-feed.xml ./output_published/package-feed.xml
        cp ./package-registry.json ./output_published/package-registry.json

    - name: Run IG Publisher Go Publish
      run: | 
        mkdir input-cache
        mv publisher.jar ./input-cache/publisher.jar
        unset DISPLAY
        java -Djava.awt.headless=true -jar ./input-cache/publisher.jar -go-publish -source . -web ./output_published -registry ./fhir-ig-registry/fhir-ig-list.json -history ./fhir-ig-history-templates -templates ./fhir-web-templates -temp ./buildtmp
    
    - name: Deploy Implementation Guide
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ROBO_OLIVER }}
        external_repository: HL7Austria/hl7austria.github.io
        publish_branch: pages
        publish_dir: ./output_published
        destination_dir: ./r5-core-${{ steps.extract_branch.outputs.branch }}

    - name: Deploy updated FHIR IG List.json
      if: success()
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ROBO_OLIVER }}
      with:
        source_file: './fhir-ig-registry/fhir-ig-list.json'
        destination_repo: 'HL7Austria/ig-registry'
        destination_folder: '.'
        user_email: 'automated@hl7.at'
        user_name: 'hl7austriabot'
        commit_message: 'HL7AT: Updated IG list json'
        destination_branch: 'test'

    - name: Deploy updated feed publication
      if: success()
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ROBO_OLIVER }}
      with:
        source_file: './output_published/publication-feed.xml'
        destination_repo: 'HL7Austria/hl7austria.github.io'
        destination_folder: './'
        user_email: 'automated@hl7.at'
        user_name: 'hl7austriabot'
        commit_message: 'HL7AT: Updated publication feed'
        destination_branch: 'pages'

    - name: Deploy updated feed package
      if: success()
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ROBO_OLIVER }}
      with:
        source_file: './output_published/package-feed.xml'
        destination_repo: 'HL7Austria/hl7austria.github.io'
        destination_folder: './'
        user_email: 'automated@hl7.at'
        user_name: 'hl7austriabot'
        commit_message: 'HL7AT: Updated package feed'
        destination_branch: 'pages'

    - name: Deploy updated package registry
      if: success()
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ROBO_OLIVER }}
      with:
        source_file: './output_published/package-registry.json'
        destination_repo: 'HL7Austria/hl7austria.github.io'
        destination_folder: './'
        user_email: 'automated@hl7.at'
        user_name: 'hl7austriabot'
        commit_message: 'HL7AT: Updated packages feed'
        destination_branch: 'pages'
        
